os:
    - linux
    - osx

language: rust
rust:
    - stable
    - beta
    - nightly

env:
    - RUST_BACKTRACE=1

matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
    fast_finish: true

install:
    - bin/setup-wasm.sh
    - bin/install-wasm-opt.sh
    - rustup component add clippy

script:
    - cargo test --verbose
    - cargo clippy --all-targets -- -D warnings
    - cargo clippy --features "concurrent" --all-targets -- -D warnings -A unused_imports
    - bin/build-wasm.sh
    - cd compressor; cargo clippy -- -D warnings; cd ..

cache:
    cargo: true
    directories:
        - $HOME/.local/bin

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/
  on:
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable"
