[package]
name = "chart"
version = "0.1.0"
authors = ["Dexter Chua <dec41@srcf.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
expect-test = "1.1.0"
